export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache
export XAUTHORITY=$XDG_CACHE_HOME/Xauthority
export VISUAL=gedit
export EDITOR=gedit
export BROWSER=qutebrowser
export FILE=thunar
export TERMINAL=urxvtc
export RXVT_SOCKET=$XDG_RUNTIME_DIR/urxvtd
export GTK2_RC_FILES=$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0
export TASKRC=$XDG_CONFIG_HOME/taskwarrior/taskrc
export TASKDATA=$XDG_CONFIG_HOME/taskwarrior
export VIT_DIR=$XDG_CONFIG_HOME/vit
export GNUPGHOME=$XDG_DATA_HOME/gnupg
export INPUTRC=$XDG_CONFIG_HOME/readline/inputrc
export RECOLL_CONFDIR=$XDG_CONFIG_HOME/recoll
export ASPELL_CONF="per-conf $XDG_CONFIG_HOME/aspell/aspell.conf; personal $XDG_CONFIG_HOME/aspell/en.pws; repl $XDG_CONFIG_HOME/aspell/en.prepl"
export QT_QPA_PLATFORMTHEME="qt5ct"
